add tube token list
iotubeproject/web-iotube-web3 pull request #107
Opened 2021-09-18 09:25 UTC by anshuomomo

2021-09-19 05:49 UTC, guo commented on public/tokenList/tube-tokens.json
> +      "chainId": 4690,
4689

2021-09-20 03:47 UTC, uu-z approved these changes

2021-09-20 03:49 UTC, uu-z requested changes

2021-09-20 03:49 UTC, uu-z commented on public/tokenList/tube-tokens.json
> +      "logoURI": "https://iotexscan.io/image/token/io10u9dv0ys93nmr7smzyptpkhlhzylt4wtqzrvld.png"
please use cdn link
https://iotexproject.iotex.io/iotex-token-metadata/master/images/io19fsq8e9krrlng4ay5gyq6q5tqfym28yq9ly0fz.png

2021-09-21 03:16 UTC, merged